name: my_study_mate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.7.0
  flutter_svg: ^2.0.0        # dipindah ke sini (gabung dependencies utama)
  flutter_lints: ^5.0.0 
  
  table_calendar: ^3.1.2     # dipindah juga ke sini (INI BENAR)

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/ui_design/
    - assets/ui_design/element_onboarding/
    - assets/ui_design/vector/
