name: my_study_mate
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.7.0
  flutter_secure_storage: ^9.2.4
  dio: ^5.9.0
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
    - assets/ui_design/
    - assets/ui_design/element_onboarding/
    - assets/ui_design/vector/
    - assets/ui_design/element_splash/LogoApp.png
    - assets/ui_design/element_splash/Union.png
    - assets/ui_design/element_welcome/Arrow.png
